<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.opengis.cite</groupId>
    <artifactId>ets-common</artifactId>
    <version>15-SNAPSHOT</version>
  </parent>
  
  <artifactId>schema-utils</artifactId>
  <version>1.9-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Schema Validation Utilities</name>
  <description>
  Provides support for validating XML representations using the following 
  schema languages: W3C XML Schema 1.0, Schematron (ISO/IEC 19757-3:2006), 
  and RELAX NG (ISO/IEC 19757-2:2008). It is also possible to access and 
  query the post-schema-validation infoset (PSVI) using the Xerces XML 
  Schema API.
  </description>
  <url>http://opengeospatial.github.io/schema-utils/</url>
  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>http://opensource.org/licenses/Apache-2.0</url>
    </license>
  </licenses>

  <organization>
    <name>Open Geospatial Consortium</name>
    <url>http://www.opengeospatial.org/</url>
  </organization>
  <scm>
    <connection>scm:git:https://github.com/opengeospatial/schema-utils.git</connection>
    <developerConnection>scm:git:git@github.com:opengeospatial/schema-utils.git</developerConnection>
    <url>https://github.com/opengeospatial/schema-utils</url>
    <tag>HEAD</tag>
  </scm>
  <issueManagement>
    <system>GitHub Issue Tracker</system>
    <url>https://github.com/opengeospatial/schema-utils/issues</url>
  </issueManagement>
  <developers>
    <developer>
      <name>R. Martell</name>
      <url>https://github.com/rjmartell</url>
      <timezone>America/Vancouver</timezone>
    </developer>
  </developers>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ssZ</maven.build.timestamp.format>
    <saxon.version>9.0.0.8</saxon.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.opengis.cite.teamengine</groupId>
      <artifactId>teamengine-spi</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opengis.cite.saxon</groupId>
      <artifactId>saxon9</artifactId>
    </dependency>
    <dependency>
      <groupId>xerces</groupId>
      <artifactId>xercesImpl</artifactId>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>

</project>
